package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/NQAI-Dev/nodepulse/pkg/store"
)

// newTestStore spins up a PersistentStore with in-memory SQLite so the
// HTTP handlers can be exercised without touching disk. The master token
// is generated by ensureMasterToken at startup and cached on the struct;
// we read it back via Store.MasterToken(), the same accessor the operator
// UI would use to display the break-glass credential.
func newTestStore(t *testing.T) (*store.PersistentStore, string) {
	t.Helper()
	s, err := store.NewPersistentStore(":memory:", "test-bot-token", 0)
	if err != nil {
		t.Fatalf("NewPersistentStore: %v", err)
	}
	return s, s.MasterToken()
}

// TestHandleInviteCreateMasterTokenAuth pins the auth contract:
// without a valid master token the handler must 401, regardless of
// body content. This is the gate that keeps random users from minting
// invites — operator-level action, not user-level.
func TestHandleInviteCreateMasterTokenAuth(t *testing.T) {
	s, _ := newTestStore(t)

	cases := []struct {
		name   string
		header string
	}{
		{"no auth header", ""},
		{"wrong token", "Bearer np_inv_garbage"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			req := httptest.NewRequest("POST", "/api/v1/invites", strings.NewReader("{}"))
			if c.header != "" {
				req.Header.Set("Authorization", c.header)
			}
			w := httptest.NewRecorder()
			handleInviteCreate(s, w, req)
			if w.Code != http.StatusUnauthorized {
				t.Fatalf("status: got %d want 401, body=%q", w.Code, w.Body.String())
			}
		})
	}
}

// TestHandleInviteCreateMintsToken covers the happy path: master token
// + empty body → fresh permanent invite. Asserts the response shape
// the bot/operator relies on (raw token + deep_link ready to share).
func TestHandleInviteCreateMintsToken(t *testing.T) {
	s, master := newTestStore(t)

	body := bytes.NewReader([]byte("{}"))
	req := httptest.NewRequest("POST", "/api/v1/invites", body)
	req.Header.Set("Authorization", "Bearer "+master)
	w := httptest.NewRecorder()
	handleInviteCreate(s, w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status: got %d want 200, body=%q", w.Code, w.Body.String())
	}
	var resp struct {
		Token          string `json:"token"`
		DeepLink       string `json:"deep_link"`
		TargetUserID   int64  `json:"target_user_id"`
		AutoCreateUser bool   `json:"auto_create_user"`
		ExpiresAt      int64  `json:"expires_at"`
	}
	if err := json.NewDecoder(w.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if !strings.HasPrefix(resp.Token, "np_inv_") {
		t.Errorf("token prefix: got %q want np_inv_…", resp.Token)
	}
	if !strings.HasSuffix(resp.DeepLink, resp.Token) {
		t.Errorf("deep_link must end with the raw token: %q vs %q", resp.DeepLink, resp.Token)
	}
	if !strings.Contains(resp.DeepLink, "t.me/nodepulse_mon_bot?start=") {
		t.Errorf("deep_link shape unexpected: %q", resp.DeepLink)
	}
	if resp.ExpiresAt != 0 {
		t.Errorf("default invite should have expires_at=0 (no expiry), got %d", resp.ExpiresAt)
	}
}

// TestHandleInviteCreateWithOptions verifies optional fields propagate
// end-to-end: target_user_id bound, auto_create_user flag set, and
// expires_in_hours translated to a real Unix timestamp in the future.
func TestHandleInviteCreateWithOptions(t *testing.T) {
	s, master := newTestStore(t)

	payload := `{"target_user_id": 42, "auto_create_user": true, "default_username": "client-acme", "expires_in_hours": 24}`
	req := httptest.NewRequest("POST", "/api/v1/invites", strings.NewReader(payload))
	req.Header.Set("Authorization", "Bearer "+master)
	w := httptest.NewRecorder()
	handleInviteCreate(s, w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status: got %d want 200, body=%q", w.Code, w.Body.String())
	}
	var resp struct {
		Token          string `json:"token"`
		TargetUserID   int64  `json:"target_user_id"`
		AutoCreateUser bool   `json:"auto_create_user"`
		ExpiresAt      int64  `json:"expires_at"`
	}
	if err := json.NewDecoder(w.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if resp.TargetUserID != 42 {
		t.Errorf("target_user_id: got %d want 42", resp.TargetUserID)
	}
	if !resp.AutoCreateUser {
		t.Errorf("auto_create_user should be true")
	}
	if resp.ExpiresAt == 0 {
		t.Errorf("expires_at should be non-zero with expires_in_hours=24")
	}

	// And the row actually landed in the DB with the right shape.
	inv, err := s.GetInvite(resp.Token)
	if err != nil {
		t.Fatalf("GetInvite: %v", err)
	}
	if inv.DefaultUsername != "client-acme" {
		t.Errorf("default_username: got %q want client-acme", inv.DefaultUsername)
	}
	if inv.TargetUserID != 42 {
		t.Errorf("inv.TargetUserID: got %d want 42", inv.TargetUserID)
	}
}

// TestHandleInviteRedeemFullFlow exercises the bot's typical path:
// mint a token, redeem it, verify the bot can now look up the bound
// user. This is the contract nodepulse-bot's `/start <token>` branch
// will depend on, so the test simulates that exact sequence.
func TestHandleInviteRedeemFullFlow(t *testing.T) {
	s, master := newTestStore(t)

	// 1. Operator mints an invite bound to user 7.
	createReq := httptest.NewRequest("POST", "/api/v1/invites",
		strings.NewReader(`{"target_user_id": 7, "default_username": "client-x"}`))
	createReq.Header.Set("Authorization", "Bearer "+master)
	createW := httptest.NewRecorder()
	handleInviteCreate(s, createW, createReq)
	if createW.Code != http.StatusOK {
		t.Fatalf("create status: got %d want 200", createW.Code)
	}
	var created struct {
		Token string `json:"token"`
	}
	if err := json.NewDecoder(createW.Body).Decode(&created); err != nil {
		t.Fatalf("decode create: %v", err)
	}

	// 2. Bot redeems with the user's chat_id.
	redeemBody, _ := json.Marshal(map[string]any{
		"token":   created.Token,
		"chat_id": 1234567890,
	})
	redeemReq := httptest.NewRequest("POST", "/api/v1/invites/redeem", bytes.NewReader(redeemBody))
	redeemW := httptest.NewRecorder()
	handleInviteRedeem(s, redeemW, redeemReq)

	if redeemW.Code != http.StatusOK {
		t.Fatalf("redeem status: got %d want 200, body=%q", redeemW.Code, redeemW.Body.String())
	}
	var redeemed struct {
		OK             bool  `json:"ok"`
		TargetUserID   int64 `json:"target_user_id"`
		AutoCreateUser bool  `json:"auto_create_user"`
		RedeemedAt     int64 `json:"redeemed_at"`
	}
	if err := json.NewDecoder(redeemW.Body).Decode(&redeemed); err != nil {
		t.Fatalf("decode redeem: %v", err)
	}
	if !redeemed.OK {
		t.Errorf("ok flag: got false want true")
	}
	if redeemed.TargetUserID != 7 {
		t.Errorf("target_user_id: got %d want 7", redeemed.TargetUserID)
	}
	if redeemed.RedeemedAt == 0 {
		t.Errorf("redeemed_at not populated")
	}
}

// TestHandleInviteRedeemErrors covers the four error branches the bot's
// error-handling code has to dispatch on. Each case asserts both the
// HTTP status code and a substring of the body so the bot doesn't have
// to pattern-match ambiguous error strings.
func TestHandleInviteRedeemErrors(t *testing.T) {
	s, master := newTestStore(t)

	// Mint one token so we can drive the already-redeemed branch.
	createReq := httptest.NewRequest("POST", "/api/v1/invites", strings.NewReader("{}"))
	createReq.Header.Set("Authorization", "Bearer "+master)
	createW := httptest.NewRecorder()
	handleInviteCreate(s, createW, createReq)
	var created struct {
		Token string `json:"token"`
	}
	_ = json.NewDecoder(createW.Body).Decode(&created)

	// First redeem succeeds.
	firstBody, _ := json.Marshal(map[string]any{"token": created.Token, "chat_id": 111})
	firstReq := httptest.NewRequest("POST", "/api/v1/invites/redeem", bytes.NewReader(firstBody))
	firstW := httptest.NewRecorder()
	handleInviteRedeem(s, firstW, firstReq)
	if firstW.Code != http.StatusOK {
		t.Fatalf("first redeem should succeed, got %d", firstW.Code)
	}

	cases := []struct {
		name        string
		body        string
		wantStatus  int
		wantContain string
	}{
		{
			"missing token",
			`{"chat_id": 1}`,
			http.StatusBadRequest,
			"token required",
		},
		{
			"unknown token",
			`{"token": "np_inv_does_not_exist", "chat_id": 1}`,
			http.StatusNotFound,
			"invite not found",
		},
		{
			"already redeemed (same chat)",
			`{"token": "` + created.Token + `", "chat_id": 111}`,
			http.StatusConflict,
			"already redeemed",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			req := httptest.NewRequest("POST", "/api/v1/invites/redeem", strings.NewReader(c.body))
			w := httptest.NewRecorder()
			handleInviteRedeem(s, w, req)
			if w.Code != c.wantStatus {
				t.Errorf("status: got %d want %d (body=%q)", w.Code, c.wantStatus, w.Body.String())
			}
			if !strings.Contains(w.Body.String(), c.wantContain) {
				t.Errorf("body missing %q: %q", c.wantContain, w.Body.String())
			}
		})
	}
}

// TestHandleInviteRedeemDistinctChats pins the security-critical
// double-spend guarantee: after chat A redeems, chat B is locked out
// with 409. Without the WHERE-redeemed_at=0 guard, both chats would
// succeed and the operator's tenant would silently accept arbitrary
// new members.
func TestHandleInviteRedeemDistinctChats(t *testing.T) {
	s, master := newTestStore(t)

	createReq := httptest.NewRequest("POST", "/api/v1/invites", strings.NewReader("{}"))
	createReq.Header.Set("Authorization", "Bearer "+master)
	createW := httptest.NewRecorder()
	handleInviteCreate(s, createW, createReq)
	var created struct {
		Token string `json:"token"`
	}
	_ = json.NewDecoder(createW.Body).Decode(&created)

	bodyA, _ := json.Marshal(map[string]any{"token": created.Token, "chat_id": 100})
	reqA := httptest.NewRequest("POST", "/api/v1/invites/redeem", bytes.NewReader(bodyA))
	wA := httptest.NewRecorder()
	handleInviteRedeem(s, wA, reqA)
	if wA.Code != http.StatusOK {
		t.Fatalf("chat A redeem: got %d want 200", wA.Code)
	}

	bodyB, _ := json.Marshal(map[string]any{"token": created.Token, "chat_id": 200})
	reqB := httptest.NewRequest("POST", "/api/v1/invites/redeem", bytes.NewReader(bodyB))
	wB := httptest.NewRecorder()
	handleInviteRedeem(s, wB, reqB)
	if wB.Code != http.StatusConflict {
		t.Fatalf("chat B redeem: got %d want 409, body=%q", wB.Code, wB.Body.String())
	}
	if !strings.Contains(wB.Body.String(), `"redeemed_by_chat_id":100`) {
		t.Errorf("response should identify the winning chat (100), got %q", wB.Body.String())
	}
}

// TestHandleInviteListMasksToken pins the privacy contract: the list
// endpoint never echoes the raw token. Operators can browse their
// invite history without worrying about the response landing in a log
// scraper or shoulder-surf capture.
func TestHandleInviteListMasksToken(t *testing.T) {
	s, master := newTestStore(t)

	// Mint two tokens, then list them.
	for i := 0; i < 2; i++ {
		req := httptest.NewRequest("POST", "/api/v1/invites", strings.NewReader("{}"))
		req.Header.Set("Authorization", "Bearer "+master)
		w := httptest.NewRecorder()
		handleInviteCreate(s, w, req)
		if w.Code != http.StatusOK {
			t.Fatalf("create %d: status %d", i, w.Code)
		}
	}

	listReq := httptest.NewRequest("GET", "/api/v1/invites", nil)
	listReq.Header.Set("Authorization", "Bearer "+master)
	listW := httptest.NewRecorder()
	handleInviteList(s, listW, listReq)
	if listW.Code != http.StatusOK {
		t.Fatalf("list status: got %d want 200", listW.Code)
	}
	body := listW.Body.String()
	if !strings.Contains(body, "token_masked") {
		t.Errorf("list response missing token_masked field: %q", body)
	}
	if !strings.Contains(body, "…") {
		t.Errorf("list response missing ellipsis mask: %q", body)
	}
	// The list response shouldn't contain any raw np_inv_ hex suffixes.
	// (We can't assert against the full token here because we don't know
	// it, but we can verify the np_inv_ prefix only appears as the
	// 12-char masked start.)
	if strings.Count(body, "np_inv_") > 2 {
		t.Errorf("list response leaked raw tokens: %q", body)
	}
}

// TestHandleInviteListRequiresMaster confirms the list endpoint is
// also master-gated — same defensible auth posture as create.
func TestHandleInviteListRequiresMaster(t *testing.T) {
	s, _ := newTestStore(t)

	req := httptest.NewRequest("GET", "/api/v1/invites", nil)
	w := httptest.NewRecorder()
	handleInviteList(s, w, req)
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("no-auth list: got %d want 401", w.Code)
	}
}
